version: "3"

services:
  influxdb:
    image: influxdb:2.7.1
    volumes:
      - influxdb-storage:/var/lib/influxdb2:rw
    env_file:
      - .env
    entrypoint: "./entrypoint.sh"
    restart: on-failure:10
    ports:
      #- ${DOCKER_INFLUXDB_INIT_PORT}:8086
      - 8082:8082
      - 8086:8086
      - 8089:8089
    networks: 
      - TIG_net

  telegraf:
    image: telegraf:1.26.3
    volumes:
      - ${TELEGRAF_CFG_PATH}:/etc/telegraf/telegraf.conf:rw
    env_file:
      - .env
    depends_on:
      - influxdb
    networks: 
      - TIG_net

  grafana:
    image: grafana/grafana-oss:9.5.1
    volumes:
      - grafana-storage:/var/lib/grafana:rw
    depends_on:
      - influxdb
    ports:
      - ${GRAFANA_PORT}:3000
    networks: 
      - TIG_net

networks:
  TIG_net:

volumes:
  grafana-storage:
  influxdb-storage:
